let clap = new Audio('./sounds/clap.wav')
let crash = new Audio('./sounds/crash.wav')
let ride = new Audio('./sounds/ride.wav')
let kick = new Audio('./sounds/kick.wav')
let snare = new Audio('./sounds/snare.wav')
let percussion = new Audio('./sounds/percussion.wav')
let closedhi = new Audio('./sounds/closed-high-hat.wav')
let openhi = new Audio('./sounds/open-high-hat.wav')

let claptwo = new Audio('./sounds/clap-two.wav')
let crashtwo = new Audio('./sounds/crash-two.wav')
let ridetwo = new Audio('./sounds/ride-two.wav')
let kicktwo = new Audio('./sounds/kick-two.wav')
let snaretwo = new Audio('./sounds/snare-two.wav')
let percussiontwo = new Audio('./sounds/percussion-two.wav')
let closedhitwo = new Audio('./sounds/closed-high-hat-two.wav')
let openhitwo = new Audio('./sounds/open-high-hat-two.wav')
